# Generated by Django 5.2.9 on 2025-12-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='audios/')),
                ('file_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='Taille en octets')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_deepfake', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('transcription', models.TextField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audio_scans',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
